export const photos = {
  'bandung-night': { id: 'bandung-night', regionId: 'bandung', src: './assets/photos/bandung-night.jpg', credit: 'dapiki moto', url: 'https://unsplash.com/photos/people-sitting-on-chair-near-store-during-night-time-RAL3lZU3j0E', theme: 'food', title: 'When the city gathers to eat', label: 'After dark', description: 'Lights, food counters and shared tables in a photograph captioned “Cibadak culinary night” by its photographer.', alt: 'Diners and food counters beneath string lights in Bandung at night.', location: 'Bandung, Indonesia', position: '50% 55%' },
  'bandung-market': { id: 'bandung-market', regionId: 'bandung', src: './assets/photos/bandung-market.jpg', credit: 'Falaq Lazuardi', url: 'https://unsplash.com/photos/woman-in-blue-and-red-floral-dress-walking-on-street-during-daytime-9SyG7TQ5PbI', theme: 'people', title: 'The rhythm of the everyday market', label: 'At the market', description: 'A moment between the fruit stalls: shopping, conversation and the small routines of everyday life.', alt: 'Shoppers browsing fruit and vegetables in a covered traditional market.', location: 'Tagged Bandung · exact market unconfirmed', position: '50% 58%' },
  'bandung-cafe': { id: 'bandung-cafe', regionId: 'bandung', src: './assets/photos/bandung-cafe.jpg', credit: 'Matiinu Ramadhan', url: 'https://unsplash.com/photos/man-standing-front-desk-inside-room-i3vmGDN_Fzg', theme: 'food', title: 'A pause at the espresso bar', label: 'Coffee & conversation', description: 'Warm wood, coffee cups and a quiet moment behind the counter at My Kopi O!, photographed in Bandung.', alt: 'A person behind an espresso machine at a wood-panelled cafe in Bandung.', location: 'My Kopi O! · Bandung', position: '50% 50%' },
  'kanazawa-kimono': { id: 'kanazawa-kimono', regionId: 'kanazawa', src: './assets/photos/kanazawa-kimono.jpg', credit: 'Ilse Driessen', url: 'https://unsplash.com/photos/woman-in-red-and-yellow-floral-kimono-standing-on-gray-concrete-floor-during-daytime-iXcfYKVXGOg', theme: 'fashion', title: 'Colour on a wooden street', label: 'Higashi Chaya', description: 'A red floral kimono against the timber of a storefront, photographed in Kanazawa’s Higashi Chaya district.', alt: 'A woman wearing a red floral kimono at a wooden storefront in Higashi Chaya.', location: 'Higashi Chaya · Kanazawa', position: '50% 58%' },
  'kanazawa-street': { id: 'kanazawa-street', regionId: 'kanazawa', src: './assets/photos/kanazawa-street.jpg', credit: 'Artem Shuba', url: 'https://unsplash.com/photos/a-person-walking-down-a-street-next-to-tall-buildings-ZuPqwRPhmY8', theme: 'people', title: 'The city at walking pace', label: 'Neighbourhood life', description: 'A narrow street, wooden facades and a person walking through the afternoon light. A quieter view of Kanazawa.', alt: 'A person walking along a narrow street between wooden buildings in Kanazawa.', location: 'Kanazawa · Ishikawa', position: '50% 70%' },
  'kanazawa-cooking': { id: 'kanazawa-cooking', regionId: 'kanazawa', src: './assets/photos/kanazawa-cooking.jpg', credit: 'Poppy Lin', url: 'https://unsplash.com/photos/man-in-black-suit-jacket--07R-aXbARI', theme: 'food', title: 'Behind the steam at Omicho', label: 'Food & everyday work', description: 'Steam catches the light around a kitchen counter at Omicho Fish Market. An everyday scene from Kanazawa’s food culture.', alt: 'Steam drifting across a kitchen counter with people preparing food at Omicho Market.', location: 'Omicho Fish Market · Kanazawa', position: '45% 45%' }
};
export const photoCollections = {
  bandung: { hero: 'bandung-night', features: ['bandung-market', 'bandung-cafe', 'bandung-night'], sidebar: ['bandung-cafe', 'bandung-night'], themes: { people: 'bandung-market', food: 'bandung-night' } },
  kanazawa: { hero: 'kanazawa-kimono', features: ['kanazawa-cooking', 'kanazawa-street', 'kanazawa-kimono'], sidebar: ['kanazawa-street', 'kanazawa-kimono'], themes: { people: 'kanazawa-street', food: 'kanazawa-cooking', fashion: 'kanazawa-kimono' } }
};
